### ISSUE TITLE
filterlist doesn't display when severside option is set to true

### ISSUE THREAD

**Issue by kenjoegolo** [gregnb/mui-datatables#1000]
## Expected Behavior
When table option `serverside` is `true` and added some `filterList` on column options - I should be able to see it when rendered.

## Current Behavior
`filterList` doesn't display when rendered.

## Steps to Reproduce (for bugs)
https://codesandbox.io/s/muidatatables-custom-toolbar-kosjv

**Comment by gabrielliwerant** [comment]
When `serverSide` is `true`, you have to use `serverSideFilterList` to designate which filters show in the interface. See the `serverside-filters` example. The code needed some way to split how to treat filters, and the single flag for `serverSide` wasn't enough because filters are currently serving double duty (they both designate what is filtered and show it visually, but with serverside, you don't want to show it before the requests are successful).

**Comment by kenjoegolo** [comment]
Closing this, thanks @gabrielliwerant
