### ISSUE TITLE
.

### ISSUE THREAD

**Issue by shawnmitchell** [gregnb/mui-datatables#1018]
.

**Comment by shawnmitchell** [comment]
![image](https://user-images.githubusercontent.com/3594613/67253980-89e7c000-f448-11e9-8da7-f9ffeb508fae.png)

**Comment by gabrielliwerant** [comment]
Looks like this issue is missing some information! I got a screenshot of a commit I didn't recognize in my email alerts for this. Could be from a different project or a fork or something. Can you find the commit you're looking for in the commit history here? Or something in the release notes? I reference all PRs that get merged in every release.

**Comment by shawnmitchell** [comment]
Yes, sorry about this. Please delete.
