### ISSUE TITLE
Expandable Rows and Custom Row Render

### ISSUE THREAD

**Issue by scottbisaillon** [gregnb/mui-datatables#1029]
I have looked through the docs and examples and can't seem to find anything regarding this.

Is there a way to hook into the implemented row expansion when using a custom row? I am using a custom row to to set styling based on content, as well as to transform the data (ex: epoch timestamp to formatted string).

If there is another way to go about doing this, I am open to suggestions as well.

Here is my current `customRowRender` function: 
```javascript
        customRowRender: data => {
            const [sessionIdentifier, sequenceNumber, type, epochTimestamp, uptime, flags, message, param1, param2, param3] = data;
            return (
                <TableRow key={`${sessionIdentifier}${sequenceNumber}`}>
                    <TableCell>Arrow here</TableCell> // Looking add the row expansion button here
                    <TableCell>{sessionIdentifier}</TableCell>
                    <TableCell>{sequenceNumber}</TableCell>
                    <TableCell>{type}</TableCell>
                    <TableCell>{epochTimestamp !== 0 ? new Date(epochTimestamp * 1000).toLocaleString() : ''}</TableCell>
                    <TableCell>{uptime}</TableCell>
                    <TableCell>{flagToString(flags)}</TableCell>
                    <TableCell>{message}</TableCell>
                    <TableCell>{lookupParam1ForEvent(type, param1)}</TableCell>
                    <TableCell>{lookupParam2ForEvent(type, param2)}</TableCell>
                    <TableCell>{lookupParam3ForEvent(type, param3)}</TableCell>
                </TableRow>
            )
        }
``` 

Thanks!

**Comment by gabrielliwerant** [comment]
Hello @scottbisaillon. At present, there isn't any way to export the expandable row functionality outside of the currently designated options/interface for it. If you're using custom rows and you want to have expandable functionality, you will have to create it yourself.

Custom rows are a bit weird in that it's less clear what kind of functionality should be ported over, since you can change the look and operation of the table so drastically by using them. Perhaps multiple uses of `customBodyRender` in column options would serve you better? I'd also be open to PRs which would add select/expand functionality into custom row renders, though it might be quite a bit of work, I'm not too sure.
