### ISSUE TITLE
horizontal table scroll titles display issue

### ISSUE THREAD

**Issue by shawnmitchell** [gregnb/mui-datatables#1036]
![Screen Recording 2019-10-28 at 3 38 12 PM](https://user-images.githubusercontent.com/3594613/67712278-0ecb6000-f99a-11e9-9623-fa190bda0952.gif)

Any idea what I messed up to cause this title bar HScroll behavior?

Thanks in advance!

**Comment by gabrielliwerant** [comment]
Hm, quite odd. There are a couple of things you can try to help me narrow down the issue.

1. Turn on the selectable row settings and see if the behavior persists
1. Not sure which version of material ui you are using, but if you switch between v3 and v4, and let me know if it appears in one and not the other

Additionally, would be good to know what your table options are and any relevant container styling around the table.

**Comment by shawnmitchell** [comment]
Turning on selectable rows makes it worse. The select boxes stay in place while the table data scrolls behind them. 

I had 
```
{
    fixedHeader: true,
    responsive: "scrollFullHeight",
}
```
set together.

When I changed `fixedHeader` to `false`, the scrolling issue was resolved. Of course now the header widths are variable, but that is bearable.

**Comment by gabrielliwerant** [comment]
I can confirm the issue. Looks like a bug to me, thanks for reporting!

**Comment by gabrielliwerant** [comment]
I've got some more insight on the issue now, and it looks like the current behavior might be intentional, as it allows the header to be fixed according to both x and y axes. For example, this is especially useful if using selectable rows and you want the select all box to follow along with scrolling. Even without that, it provides the benefit of keeping the column header above the relevant data.

However, I can also understand why this might not be desirable, so I think what I'll do is add additional options for `fixedHeader` that allows devs to specify what combination of fixed x/y behavior they want, and deprecate the old option.

**Comment by shaka0241** [comment]
I have the same issue :(

**Comment by gabrielliwerant** [comment]
PR up which should address the issue. Feel free to take a look!
