### ISSUE TITLE
Force refresh data in datatable

### ISSUE THREAD

**Issue by jkeruzec** [gregnb/mui-datatables#105]
I want to rerender existing data to make some custom cell editing on row 
I'm using mobx framework to fetch my data using @computed and stores.

I implemented onCellClick to get row in edition but my data are not changed here. I just want to rerender existing data and re render my columns passing in customRender and changing value for input value.

 ```js
onCellClick: (colIndex, rowIndex) => {
                            this.setCurrentSelectedRow(rowIndex);
                            this.fetchDeviceTypeModel(props.deviceTypeId); // HERE force fetch data to render again the datatable I'd like to do a this.refresh().
                        }
```

```js

                                customRender: (value, tableMetadata, updateValueFn) => {
                                    if(tableMetadata.rowIndex === this.currentSelectedRow) {
                                        return <input name="test" value={value}  readOnly/>
                                    }
                                    
                                    return value;
                                    
                                }
```

I managed to make it work by refetching my data but the datatable blinks.... that is annoying.

Could you provide just a "rerender", "update" or "refresh" method to render again the datatable or an attribute to force refresh in options ? 

edit : one thing I could do is to display old data while new are fetching... But it's not really a good idea I think :D

**Comment by gregnb** [comment]
Could you show me how you're managing the data you provide to MUIDataTables? My first thought is you should manage the data outside of the MUIDataTables and then provide the new data to the table like a controlled component.

**Comment by jkeruzec** [comment]
For sure :
First  I have couple of stores loaded when my component is constructed
Then I display datatables on render function with 
```
 <MUIDataTable 
                    data={this.preparedData} 
                    columns={this.columns} 
                    options={this.options}
                />
```
I load my store with async method using a computed value : 

```
// Prepare data from collection Transform list of object to simple array with order
// When data is changed and so my store, mobx refresh and compute my new data
    @computed
    get preparedData() {
        this.deviceTypeModel.deviceTechnos.get(); // Load some information with await/async
        let dataTableUtils = DataTableUtils; 
// Create array according to my collection store and my column information
        return dataTableUtils.createDataArray(deviceTechnologiesCollection, this.columns); 
    }
```

I think my problem comes from the async store with my rest API .. There is always a moment where my data is loading and I have to display something

**Comment by gregnb** [comment]
> I think my problem comes from the async store with my rest API .. There is always a moment where my data is loading and I have to display something

Ok, so you make your async request and mobx then provides the data when it is available. Then, you create that data array and pass it off to the MUIDataTable library. What do you mean by display something? 

Does the following not work well for you?
1) onCellClick -> this triggers async request 
2) async request resolves and data is returned
3) convert this with createDataArray() and pass this new data to MUIDataTable

Then, the table will reload completely because there is brand data provided

**Comment by jkeruzec** [comment]
I fixed my issue, but I'm forced to reset one store used in computed value to force mobx to re compute this store and refresh data. 

I wish there were a way to say to mobx compute again this data like a "dirty" or "changed" flag.

For what you propose, this what I'm doing here already. OnCellClick I set the currentRowSelectionId and then I trigger a reset and a fetch of my datatable data (no data has changed here!) then it triggers customRender to set my inline edition inputs but it's not ideal

**Comment by gregnb** [comment]
Could you record a small video and let me see what happens?

**Comment by jkeruzec** [comment]
Ok let's give it that to you, the issue is more visible has I add more rows on the datatable.
I think there is another feature that would be great, is to have the possibility to add a row at certain position.

Here's the capture: 

![capture](https://user-images.githubusercontent.com/3499632/43253438-4207e43c-90c5-11e8-8e23-250a09bcc0fc.gif)

**Comment by gregnb** [comment]
Sorry, I am still trying to understand. So you click on add a row, but you don't want todo anything. Maybe it was like a user mistake right? So then, what you're asking is there a way I can just re-render what was there previously?

**Comment by jkeruzec** [comment]
>  I can just re-render what was there previously?

Yes this is it : 

1. Datatable is loaded with data
2. User click on a cell or edit button
3. I need here to able to go on customRender without reloading data (because nothing changed)
4. Current selected row (I got the row ID) is rendered passing in customRender so that field changed from string to custom input. The rest is left untouched, no need to reload the full table.

**Comment by gregnb** [comment]
Ok, I got it now. Thanks.

**Problem 1)**

A cheap way around the first problem in the mean time would've been popping up a modal maybe but I understand the inline edit looks much nicer. That way if someone makes no change the data doesn't change either.

These are some good problems and I need some time to think about it.  

**Problem 2)**

This is tough because we're saying MUIDatatables is being used a controlled component and data is feed into the library right? I feel like what you're describing is blurring the lines and mixture of both.  Who is going to be in control? The developer managing the data or the library managing the data?

What are we trying to accomplish in the end? Are we trying to insert data without having to reload all over again? Problem is if the data changes MUIdatatables has to regenerate all sorts of settings. Needs to figure out which rows should be displayed, total row counts, filters, etc.

**Comment by RickyCh** [comment]
Hi jkeruzec. Happened to see the above video. After clicking "Edit" button, "Market share" column becomes editable with some tags/labels in the table cell. It looks really nice.
Could you please indicate how did you implement those tags under the "Market share" column? Thanks!

**Comment by RickyCh** [comment]
> Ok let's give it that to you, the issue is more visible as I add more rows on the datatable.
> I think there is another feature that would be great, is to have the possibility to add a row at certain position.
> 
> Here's the capture:
> 
> ![capture](https://user-images.githubusercontent.com/3499632/43253438-4207e43c-90c5-11e8-8e23-250a09bcc0fc.gif)

Hi jkeruzec. Happened to see the above video. After clicking "Edit" button, "Market share" column becomes editable with some tags/labels in the table cell. It looks really nice.
Could you please indicate how did you implement those tags under the "Market share" column? Thanks!

**Comment by DTupalov** [comment]
@gregnb 
I've ran into this problem, too. I have custom components (like toolbar and cell render) inside which are props from my parent component (like `loading` prop). And with same `data` and `columns` props, table wan't rerender, so my custom components have wrong state. 

Maybe the good solve is to check, if user passed custom components, then table will rerender? 

I've tried implement this fast, but there is some problems with updating table. Problems are with recalculating of current state (selections, sort etc.). We have only functionality for a new table with new state.

It is critical need, because I'm using this table like uncontrolled component.

Anyway, I will try to resolve this problem and write summary or PR :)

**Comment by jkeruzec** [comment]
@RickyCh sorry for delay, for tags, I used [react-select](https://react-select.com/home) that is very useful for this.

@DTupalov I'm just eager to see that and @gregnb I don't if you had time to think about this ?

For the moment, I still use this solution, I only did some improvements on loading time of my component so that users cannot really see this reloading time.

**Comment by RickyCh** [comment]
@jkeruzec Thanks for your response. I also found react-select very useful for filtering.

**Comment by patorjk** [comment]
Closing issue due to age. Props/state issues fixed in latest version of the table.
