### ISSUE TITLE
White spaces of search text

### ISSUE THREAD

**Issue by LusineGasparyan98** [gregnb/mui-datatables#1055]
## Expected Behavior
   If we are searching for something in the table and write white spaces before or after the search text it is not finding any data. It would be better if white spaces existing in the beginning and end of the search text are ignored during the search

## Current Behavior
 Now searching data writing search text with whitespaces before and after the main search text brings the wrong search and no data is found.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |  4.4.0       |
| MUI-datatables  |    2.12.4     |
| React        |    16.9.0     |
| browser      |     Chrome    |

**Comment by gabrielliwerant** [comment]
Hm, I'm not sure it's wrong to include the space in the search filter. Searching for data is a bit different than searching in a search engine. I would not expect a datatable to be context aware and understand what I'm looking for. Tables can hold all sorts of data, and for many different kinds of data, spaces, even trailing or leading spaces, might be important. For that reason, and because this would be a breaking change, I think I'd prefer to let devs handle this behavior for themselves. You can specify custom search behavior with the `customSearch` option.

**Comment by Kmcgee92** [comment]
You could make an option? like customSearchOptions: {trimWhiteSpace:true}
