### ISSUE TITLE
Mobile view spacing has changed in recent version and height issues

### ISSUE THREAD

**Issue by TriStarGod** [gregnb/mui-datatables#1095]
As seen in https://codesandbox.io/s/currying-bush-kcl1g , if you shrink the width, the spacing changes for version 2.13.1 
![image](https://user-images.githubusercontent.com/8272754/70113834-3613ed80-1628-11ea-9987-2fcf34446fdd.png)

compared to version 2.12.4. 
![image](https://user-images.githubusercontent.com/8272754/70113881-60fe4180-1628-11ea-8b47-c4f7a36a46e2.png)

Unsure if this was intended.

Also, I can't figure out to how to make the table fill the parent container. If the table contained less than 10 items, the table shrinks. I would like my tables that are next to each other horizontally to have equivalent height. Any suggestions?

| Tech         | Version |
|--------------|---------|
| Material-UI  |    4.7.1     |
| MUI-datatables  |   2.13.1      |
| React        |    16.12.0     |
| browser      |     Chrome x64    |
| etc          |    Windows x64    |

**Comment by gabrielliwerant** [comment]
Hey @TriStarGod, thanks for reporting this issue. I was able to verify, and have a fix ready as a patch. It was not intentional.

Regarding your other question, you may want to open a new issue for it if it remains a problem for you, as this issue will close after the fix is merged. What I think you'd need to do is override the `maxHeight` style for the responsive `scrollMaxHeight` option. You'll need to input a max height that is small enough to include a table with the minimum items you're looking for, which should make all the tables the same size (in height).

**Comment by TriStarGod** [comment]
@gabrielliwerant Thanks. I opened issue #1099

**Comment by patorjk** [comment]
Adding this rule:

    padding: 6px 0 0 0

To the "cellStacked" and "responsiveStacked" classes in TableBodyCell.js seems to fix this in both 2.12.1 and 2.12.3. You can try it by manually adding the rules. The cells were inheriting large padding which was messing up the height parameter.

@gabrielliwerant It may be worth reverting https://github.com/gregnb/mui-datatables/pull/1096 and instead adding the padding rule above since the new PR causes the styling issues described here: https://github.com/gregnb/mui-datatables/issues/1097
