### ISSUE TITLE
Dynamically computed field not shown in downloaded CSV

### ISSUE THREAD

**Issue by KrzysztofMadejski** [gregnb/mui-datatables#1104]
I have a dynamically computed field using `customBodyRender` to compute it from other fields in the row. This column is shown in csv download, but without values. 

## Expected Behavior
I'm wondering what should be the expected behaviour. If current behaviour is intended then let this issue be closed and stay as tutorial.

I guess a way to implement it would be to use displayData for a column in case is it not present in original data. 

I saw some bugs around customBodyRender and a PR using data instead of  displayData: https://github.com/gregnb/mui-datatables/pull/287 

If implemented it could be done here: https://github.com/gregnb/mui-datatables/blob/29b92995d29745808c9e46458580b2401fa2744b/src/components/TableToolbar.js#L95-L134 

## My workaround (or just a way to do it)

ColumnDef:
```
{
        name: 'duration',
        label: 'Duration',
        options: {
          filter: false,
          sort: false,
          customBodyRender: (
            value: any,
            tableMeta: MUIDataTableMeta
          ): string => {
            return this.getDuration(tableMeta.rowData);
          }
        }
      }
```

and then also inserting the value in custom onDownload:
```
      onDownload: (buildHead, buildBody, columns, data:{data: any[];}[]) => {
        // fill in duration
        data.forEach(row => {
          row.data[row.data.length-1] = this.getDuration(row.data);
        });
        
        return buildHead(columns) + buildBody(data)
      },
```

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |      3.9.2   |
| MUI-datatables  |    2.12.0"     |
| React        |    16.8.6     |

**Comment by gabrielliwerant** [comment]
Display data in the context of the download options means that data fields that are visible to the user. It does not guarantee the same values, as it is not computing custom renders when downloading, as you have found out. It pulls from the original data object.

Using `displayData` won't work if you are returning a component from the custom render, because this shows up in the data as a react element object, and they can be any size and shape that a component can be, so there is no way to retrieve the intended data from it (it's also possible the developer intent is a visual indication only, in which case it should not be downloaded as part of a csv). So actually, in order to properly pull data from a custom rendered field, according to the wishes of the developer, we'd need more options and a more complicated API to achieve this. We could check if the custom render returns a string, and allow strings to be used, but it represents a breaking change from how it operates now, so even this would not be easy to implement.

What I recommend, is using the `onDownload` callback, as you have done, to specify exactly what you want to appear in the downloaded csv.

**Comment by KrzysztofMadejski** [comment]
Thanks for feedback! So I'm closing it, leaving as reference.
