### ISSUE TITLE
Invalid attempt to spread non-iterable instance

### ISSUE THREAD

**Issue by xStorm11** [gregnb/mui-datatables#1118]
Hello, i'm currently working on a project using mui-datatables and i needed to comment the following code because it crashes the project when i use the "Select/Unselect all":
![image](https://user-images.githubusercontent.com/28924768/70718022-6114d600-1ce7-11ea-88a1-13ceb6916185.png)

I didn't change the code, i even tried to use mui-datatables on other projects and i had the same error.

## Expected Behavior
Select/Unselect all like the codesandbox example allows.

## Current Behavior
This is what happens when i click on the checkbox:
![image](https://user-images.githubusercontent.com/28924768/70718524-44c56900-1ce8-11ea-88ce-474dcca06fa9.png)

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    0.3.9    |
| MUI-datatables  |  2.12.4   |
| React        |    16.8.6     |
| browser      |  Chrome, Firefox   |

**Comment by gabrielliwerant** [comment]
Hello @xStorm11, is your version of Material-UI given in this ticket the actual version you are using to produce the error? If so, note that this version is very out of date, and could be the source of your problem. See if upgrading to the latest fixes your issue (though you may need to change some other things to get it to work). If the problem persists after upgrading your Material-UI version, then I'll need to see a minimal codesandbox example that demonstrates the issue so I can find out what may be happening.

**Comment by patorjk** [comment]
@xStorm11 @gabrielliwerant I can verify this. I've fixed this in PR https://github.com/gregnb/mui-datatables/pull/1077/ - it only occurs if you update **babel** and other packages though. It won't occur in the current setup. It's due to this line:

https://github.com/gregnb/mui-datatables/pull/1077/files#diff-4f4aff53b74d2c551e37786d32b82e3aL1164

"prevState.selectedRows" shouldn't be spread over. If you do a console.dir on it, you'll see why it can't be spread over (see https://github.com/gregnb/mui-datatables/pull/692#issuecomment-529515167 for more info). The version of babel this project uses just ignores the error, but it pops up if you update babel.

This PR also describes the issue: https://github.com/gregnb/mui-datatables/pull/692 (but it gives a faulty solution)

And actually, my response in that PR better explains exactly what is happening.

**Comment by xStorm11** [comment]
First of all, thank you very much for answer me @gabrielliwerant and @patorjk . 
I follow the changes @patorjk made on newRows and it fixes my problem. I knew this was something wrong with babel but i only had this issue using mui-datatable.
Once again, thank you!

**Comment by gabrielliwerant** [comment]
You're welcome @xStorm11.

Keeping this open until the fix is merged in, so it can be tracked.

**Comment by patorjk** [comment]
Fixed as of version 3 of the table.
