### ISSUE TITLE
Download CSV feature not working with customBodyRender

### ISSUE THREAD

**Issue by maquintal** [gregnb/mui-datatables#1129]
## Expected Behavior

When downloadcsv with column array it renders [Object,object] instead of a plain text
I found an existing issue,
https://github.com/gregnb/mui-datatables/issues/275

## Steps to Reproduce (for bugs)

1. Click Download CSV
2. open excel file
3. Array coumn should be plain text but I'm having [object, object]
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |  "@material-ui/core": "4.6.1",       |
| MUI-datatables  |"@types/mui-datatables": "^2.12.2",  "mui-datatables": "^2.10.2",       |
| React        |   "react": "^16.12.0",      |
| browser      |  Chrome Version 79.0.3945.79 (Build officiel) (64 bits)       |
| TypeScript          | "typescript": "^3.3.3",        |

**Comment by sli** [comment]
Just ran into this issue myself and can confirm it. Without a render function for CSV downloads, the only way to make more complex data CSV-friendly is by updating values by index which sounds incredibly rickety.

I don't know if customBodyRender is the best solution however, because it can be used by the table to render table data as small components, which aren't going to serialize for CSV nicely. There might need to be a customCsvRender option instead.

**Comment by maquintal** [comment]
Thank you for your reply, I really appreciate it

Have a great day

**Comment by gabrielliwerant** [comment]
Hey @maquintal. I need more steps to reproduce the issue. Not sure what you mean by "array column." Can you provide a (simple and small) sample data set that I can use to create the breakage?

**Comment by gabrielliwerant** [comment]
@sli `onDownload` already allows you to customize the entire output of the csv.

**Comment by maquintal** [comment]
sure, here my json data, note that the issue is on the controlmJobRequest, which is my array-column

{
          "requestId": "CTRM001377",
          "id": "1377",
          "requesterDetails": {
            "fullName": "Full Name",
            "department": "Department"
          },
          "doerDetails": null,
          "approverDetails": null,
          "priority": "standard",
          "effectiveDate": "2019-12-31 -05",
          "requestStatus": {
            "status": "Submitted"
          },
          "controlmJobRequest": [
            {
              "jobName": "POOOD898989",
              "jobType": "script",
              "actionType": "create"
            }
          ]
        },
and here's the download result, note that hided columns do not have issues, only the controlmJobRequest

![image](https://user-images.githubusercontent.com/45339322/71622606-e849c100-2ba4-11ea-8005-dc541a579ab2.png)

**Comment by gabrielliwerant** [comment]
Hey @maquintal, as you might have noticed, you have an array of objects, which is not supported. Only arrays of strings and numbers are supported.

**Comment by tjatwood** [comment]
I want to confirm the expected behavior of the CSV download with customBodyRender to make sure I'm not missing something. My expectation is that if I use customBodyRender on a column that takes in an array but outputs a string (e.g. `customBodyRender: (arrVal) => value.join(', ')`) I would expect that the CSV would also contain the string output and not [object Object]. Is that what I should expect or will I need to use `onDownload()` in that case?

**Comment by gabrielliwerant** [comment]
@tjatwood See the documentation for `downloadOptions` and the `csv-export` example. You have to set options to use displayed values, otherwise the table does not know which set of data you intended.

**Comment by tjatwood** [comment]
Thanks! I was able to use onDownload() to write a data interceptor that transforms the data based on customBodyRender() again before passing it to the CSV output.

**Comment by nilupulheshan1995** [comment]
@tjatwood @gabrielliwerant could you please tell me where can I found a code example..

**Comment by wjonesLACity** [comment]
Hi @tjatwood do you mind showing us an example of how you used onDownload to resolve this issue? I'm in the same boat that you were in. It would be greatly appreciated!

**Comment by ChristopheVandePoel** [comment]
@nilupulheshan1995 @wjonesLACity here's a fix i just did for this:

your column definition should define a new `option` key called (in my example) `toStringOverride`:
```typescript
const columns = [{
    name: 'allUserNames',
    label: 'Names',
    options: {
        toStringOverride: (rawDataValue: Users[]) => {
             rawDataValue.map(user => user.name).join(', ') // or whatever else you need that flattens your data
        }
    },
}
```

Which you can then use in the `onDownload` callback:
```typescript
  onDownload: (buildHead, buildBody, columns, data) => {
    const alteredData = data?.map((row, index) => ({
      index,
      data: row?.data?.map((field, index) => {
        // look for the existence of a toStringOverride on the matching column for this field:
        const mapper = columns?.[index]?.toStringOverride
        // And apply it, if it exists:
        return mapper ? mapper(field) : field
      }),
    }))

    // Taken from sourcecode:
    return `${buildHead(columns)}${buildBody(alteredData)}`.trim()
  },

```

This assumes that you are okay with adding that custom `toStringOverride`. If not, you can always try to piggyback off of the `customBodyRender` function in exactly the same way, but then you will need to go check if all of them serialize properly (which is pobably not the case for a react app).

edit: sorry for the conditional chain madness in that example, i copied it from a TS codebase, since they are all any's, I just throw them in there and move on :)

**Comment by parassanghani6** [comment]
Simply we can use same function as datatable using to render custom body.

```
onDownload: (buildHead, buildBody, columns, data) => {
    const alteredData = data?.map((row, index) => ({
      index,
      data: row?.data?.map((field, index) => {
                if (columns[index].customBodyRender) {
                    return columns[index].customBodyRender(field)
                }
                return field
            }),
    }))
    return `${buildHead(columns)}${buildBody(alteredData)}`.trim()
  },
```

**Comment by ChristopheVandePoel** [comment]
@parassanghani6 sorry for the necro reply, but that will only work when your customBodyRender returns a serializable result which, when you render icons or something in that location, won't be the case. It will output `[object Object]` again, like described above.
