### ISSUE TITLE
onRowsSelect: allRowsSelected doesn't give right output

### ISSUE THREAD

**Issue by jose-donato** [gregnb/mui-datatables#1156]
allRowsSelected is wrongly calculated onRowsSelect

## Expected Behavior

I have a table with three items. If select all three items from the table and remove the select (click checkbox again) from one (the middle one, for example), the **allRowsSelected** should contain the first and last items of the list.

## Current Behavior

The **allRowsSelected** array contains the item that I deselected.

## Steps to Reproduce (for bugs)

1. Check all items from the table
2. Deselect the one of the items

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |   4.5.1      |
| MUI-datatables  |  2.13.3       |
| React        |   16.11.0      |
| browser      |      79.0.3945.117    |

I will try later today to do a pull request with a possible fix.

**Comment by gabrielliwerant** [comment]
I'm unable to verify this on my end, as it looks like it's working to me. I'll need a codesandbox with a minimal example to reproduce the issue.

**Comment by jose-donato** [comment]
[codesandbox link](https://codesandbox.io/s/busy-wildflower-7yud5?fontsize=14&hidenavigation=1&theme=dark
)
Here you go.
(btw, I've sent you an email because I'm having some problems on running mui-datatables locally and want to contribute)

**Comment by gabrielliwerant** [comment]
There isn't anything to see at the sandbox link except the default starter code. I think you forgot to add your changes.

**Comment by jose-donato** [comment]
[codesandbox link](https://codesandbox.io/s/busy-wildflower-7yud5?fontsize=14&hidenavigation=1&theme=dark)
should be fine now, sorry.

**Comment by gabrielliwerant** [comment]
So it looks like the issue is with line 24: `onRowsSelect: (allRowsSelected) => {`.

You have only declared the first argument and the callback actually has two. The second argument is the one that gives you the remaining rows while the first is the one that gives you currently selected row. Since all you have is the first, it's treating it like the first argument. If you want to access the second, then you need to specify both arguments. You can see an example in `selectable-rows`.

**Comment by jose-donato** [comment]
You are totally right. Just tried it and all good now!
Thanks.
