### ISSUE TITLE
Bug Using MUIDataTable 2.14 using scrollFullHeightFullWidth in CardContent

### ISSUE THREAD

**Issue by Vn-ChemGio** [gregnb/mui-datatables#1163]
When using MUIDataTable 2.14 with scrollFullHeightFullWidth  option 
I found a bug :
![image](https://user-images.githubusercontent.com/25608423/72682963-9510c180-3b05-11ea-867e-d909a26f93d1.png)

Online demo here:  https://codesandbox.io/s/muidatatables-custom-toolbar-j7i8x

**Comment by gabrielliwerant** [comment]
Hey @Vn-ChemGio, I don't think this qualifies as a bug, just a property of the new option. You cannot use `scrollFullHeightFullWidth` and cleanly nest the table inside of anything else because it is using `position: absolute` to do it. If you want nested behavior with the containers, you have to use a different responsive option.
