### ISSUE TITLE
The CodeAndSandBox examples are broken

### ISSUE THREAD

**Issue by JuanmaMenendez** [gregnb/mui-datatables#1185]
The CodeAndSandBox examples are broken

## Steps to Reproduce (for bugs)

- Go to https://codesandbox.io/embed/xrvrzryjvp?autoresize=1&hidenavigation=1

- You will see: 

"ModuleNotFoundError
Could not find module in path: '@babel/runtime/helpers/builtin/interopRequireDefault' relative to '/node_modules/@material-ui/core/Paper/index.js'"

**Comment by gabrielliwerant** [comment]
So, this library could use a demo website that would illustrate many examples, but it's a lot to build and maintain for me at this point, so probably not something I could do for a while. I also can't directly update that example because I don't own that codesandbox.

I should probably put up a new example and remove the old one.

**Comment by mxmlnglt** [comment]
Ah, so this is the same Codesandbox as the one linked on this website: https://libraries.io/github/gregnb/mui-datatables
Maybe an old version of the Github home page (aka the README)?

Because now from https://github.com/gregnb/mui-datatables it's https://codesandbox.io/s/github/gregnb/mui-datatables and although it's a bit long to load (all the compiling & tests & stuff..) you can browse each example in the embedded browser...

**Comment by patorjk** [comment]
After thinking a bit, I think making people wait a while may discourage them from poking around. I've updated the Demo section to have both a link to a lightweight example as well as a link to the full repo's worth of examples.

Also, looks like the codesandbox in the original issue is mistakenly pointing to Material UI v1, which is why it wasn't working.

**Comment by mxmlnglt** [comment]
That's great, thanks!
