### ISSUE TITLE
How to change style (color) of the toolbar icon on hover?

### ISSUE THREAD

**Issue by Leocete** [gregnb/mui-datatables#1343]
Hi all! I'm currently trying to change the color of a toolbar icon on hover:
![image](https://user-images.githubusercontent.com/37488015/84881841-15c4f100-b097-11ea-9e71-d9e0c6a5be08.png)

How it could be done?
Thanks in advance

**Comment by wdh2100** [comment]
ref : https://material-ui.com/customization/theming/

```jsx
import React from "react";
import MUIDataTable from "mui-datatables";
import { createMuiTheme, MuiThemeProvider } from '@material-ui/core/styles';

const theme = createMuiTheme({
  palette: {
    primary: {
      light: '#757ce8',
      main: '#3f50b5',
      dark: '#002884',
      contrastText: '#fff',
    },
    secondary: {
      light: '#ff7961',
      main: '#f44336',
      dark: '#ba000d',
      contrastText: '#000',
    },
  },
});

class BodyCellExample extends React.Component {

  render() {

    return (
      <MuiThemeProvider theme={theme}>
        <MUIDataTable title={"ACME Employee list"} data={data} columns={columns} options={options} />
      </MuiThemeProvider>
    );

  }
}
```

**Comment by patorjk** [comment]
The table uses the theme.palette.action.hover in the theme. Here's an example:

https://codesandbox.io/s/muidatatables-custom-toolbar-hycfx?file=/index.js

One tricky point: If your table has selectable rows, you also have to keep the secondary.main color in mind, because the material-ui TableRow component factors that color in when determining the color of rows that are selected and hovered over:

https://github.com/mui-org/material-ui/blob/next/packages/material-ui/src/TableRow/TableRow.js#L20
