### ISSUE TITLE
Perfomance issue using serverSide and onSearchChange

### ISSUE THREAD

**Issue by bernatvadell** [gregnb/mui-datatables#1369]
## Current Behavior

I've modified the original sandbox with the performance problem I'm having.

Simply, by activating serverSide, and assigning it the search callback that only assigns the new value using hook useState, causes a rendering that generates some lag when writing.

My English is quite bad, and I think it is best to check the sandbox that I leave below, and try to write relatively quickly.

[![Edit MUIDatatables - Custom Toolbar](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/muidatatables-custom-toolbar-4grmm?fontsize=14&hidenavigation=1&theme=dark)

**Comment by patorjk** [comment]
It's because you're updating App's state and App is re-rendering every time you type a key. To mitigate this, for server-side use it's recommended to use the debounceSearchRender for your search. Here's a modified codesandbox showing the updated example:

https://codesandbox.io/s/muidatatables-custom-toolbar-0xef5?file=/index.js

The two new lines are:

    import MUIDataTable, { debounceSearchRender } from "mui-datatables";

    // this goes in the options
    customSearchRender: debounceSearchRender(500)

**Comment by bernatvadell** [comment]
Solved with that!

Thanks mate!
