### ISSUE TITLE
MUIDataTable versions available on Codesandbox are not on Github

### ISSUE THREAD

**Issue by mxmlnglt** [gregnb/mui-datatables#1373]
Recent versions usable in Codesandbox differ from the ones listed (published/released?) on Github: https://github.com/gregnb/mui-datatables/releases
i.e.
- 3.1.0
- 3.0.1
- 3.0.0
- 3.0.0-beta.2
- 3.0.0-beta.1
- 3.0.0-beta.0
- 2.15.0
- and so on...

Here's on Codesandbox:
![image](https://user-images.githubusercontent.com/29626929/85527257-00a61000-b60b-11ea-9678-6e5dd217b2c3.png)
There are additional:
- 3.1.3
- 3.1.3-beta.0
- 3.1.2
- 3.1.2-beta.1
- 3.1.2-beta.0
- 3.1.1

How is it possible?

**Comment by patorjk** [comment]
A release is a manual process done from github, and a new version is done by publishing to npm. When doing a release, an email goes out to those who are watching the repo. I haven't done releases for beta versions as those are just for testing (or for a particular user to test out a solution to an issue). There were a few hiccups with the draggable columns feature in the 3.1.0 release. I wanted to provide fixes quickly but I didn't want people to get spammed with emails each time a patch release went out. Typically I will do a release for a patch version, but since there were a few that happened close together I didn't.

**Comment by mxmlnglt** [comment]
OK. But how do you explain there are so many versions on Codesandbox?

**Comment by patorjk** [comment]
Those are all of the versions that have been published to npm. You can see the same list by going here:

https://www.npmjs.com/package/mui-datatables

And clicking the versions tab.

This repo's master branch currently pointing to version 3.1.3. 

The reason there aren't releases for 3.1.1-3 is because they happened close together to fix some bugs with a new feature. If you're interested, I can do a release for version 3.1.3, however, there's not a whole lot of benefit unless you want to download a zip of the code from github.
