### ISSUE TITLE
How to remove the "not being used for nested data anymore" warning message?

### ISSUE THREAD

**Issue by mxmlnglt** [gregnb/mui-datatables#1432]
Since v3 there's now a warning about column names with a dot not being used for nested data anymore:
> `Columns with a dot will no longer be treated as nested data by default. Please see the enableNestedDataAccess option for more information: https://github.com/gregnb/mui-datatables#options`
> ref. https://github.com/gregnb/mui-datatables/blob/master/docs/v2_to_v3_guide.md#nested-data-is-off-by-default

But we are using columns names with a dot **on purpose** (i.e. not for referencing nested data) e.g.
```
  {
    name: "Ref. Something",
    options: {
      display: true,
      filter: false,
      sort: true,
    }
  },
```
... and then we get the warning for every single column in this case (which is too much).

How do we avoid this?

**Comment by patorjk** [comment]
You have a couple of options:

1. Use a name without a dot but also use the label field. The label will be what’s displayed in the table.
2. There is an undocumented option called consoleWarnings. Set it to false and you won’t see any console warnings. The negative to this is you won’t know about any future deprecation (though I don’t foresee any - however, this is not something I recommend).
3. In the next version (3.3.0), consoleWarnings will take a Boolean or a function (you can see this in the test PR that’s there now). With the function, you could pick and choose which messages you wanted to ignore. It’ll most likely be added to the docs then, however, I’m still thinking about the best implementation for this. I may assign deprecation notices a number, that way it’d be easier to ignore particular messages.

**Comment by patorjk** [comment]
Actually, after thinking about this a little more, rather than officially expose that option, I'm just going to remove that deprecation notice in [3.3.0](https://github.com/gregnb/mui-datatables/pull/1434). It's the only deprecation notice that can't be removed by updating code, and it was introduced in version 3.0.0 and documented in the [upgrade guide](https://github.com/gregnb/mui-datatables/blob/master/docs/v2_to_v3_guide.md). I think users expecting it to be on by default will know to check that guide or that option's value, and keeping the deprecation notice will just discourage people from putting dots in column names.

**Comment by patorjk** [comment]
Notice for this removed in 3.3.0

**Comment by mxmlnglt** [comment]
OK, great!!! Thanks.
