### ISSUE TITLE
Scrollbar y impossible to pull

### ISSUE THREAD

**Issue by stamahto** [gregnb/mui-datatables#1504]
When i pass option: "tableBodyMaxHeight" a scroollbar on right side is created, to prevent the table from overflowing outside the user screen, but it can't be clicked to pull (down, up). Now to get lower rows, you need to use mouse wheel.
To avoid this problem, the table must have padding from right, then the scrollbar is clickable.

## Bug
I found that this problem is caused by a fixed width of div with class="PrivateSwipeArea-root-110 PrivateSwipeArea-anchorRight-112", which is set to 20px.

**Comment by patorjk** [comment]
I'm unable to re-create this issue: https://codesandbox.io/s/muidatatables-custom-toolbar-rvmcj?file=/index.js

**Comment by stamahto** [comment]
Hi, I figured it out. It does this if there is a swipeable drawer on the page: [https://codesandbox.io/s/muidatatables-custom-toolbar-forked-gh76n?file=/index.js](url)

**Comment by patorjk** [comment]
I don't see the scrollbar in that codesandbox.

**Comment by stamahto** [comment]
Because you have a higher resolution/monitor. Here it is adjusted for multiple records, to make the table scrollbar: https://codesandbox.io/s/muidatatables-custom-toolbar-forked-gh76n?file=/index.js

**Comment by patorjk** [comment]
Now I see. The issue appears to be due to the SwipeableDrawer component. If you check out the dev tools, you can see that it overlaps where the scrollbar is:

![swipe](https://user-images.githubusercontent.com/521224/92604285-58552e80-f27e-11ea-98c3-17e0f300b40d.png)

That's why you can't grab the scroll bar, the component is on-top of it. I would say this isn't a mui-datatables issue, but rather an issue with how that component works. If you're going to include it, you'll need to add some padding on the right side of the table.
