### ISSUE TITLE
Fixed title and header with tableBodyHeight 100%

### ISSUE THREAD

**Issue by data-handler** [gregnb/mui-datatables#1555]
## Expected Behavior
    When setting the tableBodyHeight to '100%' title and header cells should remain fixed

## Current Behavior
    When setting the tableBodyHeight to '100%' title and header cells scroll off screen

## Link to example
[sandbox](https://t4q0h.csb.app/)

**Comment by patorjk** [comment]
The issues seen here appear to be due to the SplitterLayout component, which uses flexbox. The height/maxHeight parameters simply set the height of a div inside of the table. 

You'll need to do some CSS adjustments to get it fit correctly, example:

https://codesandbox.io/s/silly-nightingale-wj4pr?file=/src/App.js

**Comment by data-handler** [comment]
Thank you @patorjk 

Your solution works perfectly

**Comment by carlos-montano-paynalli** [comment]
@patorjk Hello, seems that the sandbox is no longer available, could you please re upload it?
