### ISSUE TITLE
Columns not rendering nested object data when upgrading to 3.0.0

### ISSUE THREAD

**Issue by michael-alterio** [gregnb/mui-datatables#1556]
After upgrading our app from 2.15.0 to 3.0.0, we are unable to display column data when setting nested object as the name in custom column. In 2.15.0, details.code returns data ... but in 3.0.0 this returns null. Can you please investigate and fix?

  const rulesColumns: RulesColumnsType[] = [
    {
      name: "ruleName",
      label: "Name"
    },
    {
      name: "details.code",
      label: "Code"
    }
 ]

**Comment by patorjk** [comment]
You need to add the following to your options object:

```
var options = {
    enableNestedDataAccess: "."
};
```

There was previously an issue where people who had dots in their column names would have issues (not realizing that it lead to a specific behavior), so the nested data feature was turned off by default. In version 3.0.0 you should see a console message letting you know that you need to turn the feature on. In later versions of 3.x this console message was removed since it was bothering people who wanted to use dots in their column names.

More info: https://github.com/gregnb/mui-datatables/blob/master/docs/v2_to_v3_guide.md

**Comment by michael-alterio** [comment]
Thank you! That solves it :)

**Comment by michael-alterio** [comment]
@patorjk unrelated ... but can I add tableBodyMaxHeight to theme override instead of options? If so, how would I access this under MuiDataTable?

**Comment by patorjk** [comment]
Yes, you'd just want to target the MUIDataTable-responsiveBase class. The max height, if included, just gets placed onto the same div as the one that has that class:

https://github.com/gregnb/mui-datatables/blob/master/src/MUIDataTable.js#L1978

**Comment by michael-alterio** [comment]
@patorjk Thank you! One last question ... I think ;) If I combine two columns into one, is there an option where I can set to sort column by one of these (e.g. I combined date/time + user into one column) ... but I'd like to sort by publishedDateTime.

`    {
      name: "publishedData",
      label: "Published",
      options: {
        sort: true,
        customBodyRender: (value, tableMeta) => {
          const publishedByUser = history[tableMeta.rowIndex].metadata?.publishedByUser
          const publishedDateTime = history[tableMeta.rowIndex].metadata?.publishedDateTime
          return (
            <>
              {publishedByUser &&
                `By ${publishedByUser}`
              }
              {(publishedByUser && publishedDateTime) &&
                <br/>
              }
              {publishedDateTime &&
                formatDateTime(publishedDateTime)
              }
            </>
          )
        }
      }
    },`
