### ISSUE TITLE
Clarification on onRowSelect option

### ISSUE THREAD

**Issue by brianpmaher** [gregnb/mui-datatables#163]
From the README:
> Callback function that triggers when row(s) are selected. function(currentRowsSelected: array, rowsSelected: array) => void

What is the difference between `currentRowsSelected` and `rowsSelected`?

**Comment by gregnb** [comment]
Right, good question. I'll explain both:

currentRowsSelected: I think at one time I was trying to plan ahead incase we would ever need to account for somehow one or many rows being selected at the same exact time. Because it would need to potentially support more than one entry I made it an array. 

rowSelected: It means all the rows currently selected. 

I think the README could be more clear if we updated it to read like:

```
Callback function that triggers when row(s) are selected. function(currentRowsSelected: array, allRowsSelected: array) => void
```

@brianpmaher Would you want to send in a PR to fix this?

**Comment by brianpmaher** [comment]
So `currentRowsSelected` contains only the newly selected row(s)?

> @brianpmaher Would you want to send in a PR to fix this?

Yeah, I can do that.  I just want to make sure I'm totally clear on the differences.
