### ISSUE TITLE
Searching doesn't find rows with complex content

### ISSUE THREAD

**Issue by rooby** [gregnb/mui-datatables#169]
It seems like searching doesn't work if you have cell content that is more complex than a string.

For example if I am using react router and have cell with a link in it, like this:

`<Link to={"/link-route"}>Link text</Link>`

and I search for "Link text", it will not match that row.

**Comment by gregnb** [comment]
This is not an easy problem to solve. As it stands today the library will search for a value property which works well for most input like components. Other than that we would need to render and then save the value of each of these complex components so they could be searched.

With that said it’s not something I’m looking to do since it’s an expensive operation
