### ISSUE TITLE
Make availability to hide column from MUIDataTableViewCol, but show in table

### ISSUE THREAD

**Issue by zhdanouskikh** [gregnb/mui-datatables#289]
## Expected Behavior
It will be a good idea to hide column from View Columns menu, and always show it in table itself.

## Current Behavior
We can't provide an option for columns property not to show column in View Columns menu.

**Comment by zhdanouskikh** [comment]
It's an improvement/feature.

**Comment by diegochavez** [comment]
I think because the current feature is just about displaying columns, should be called in some way a exclude array of columns names, this could be removed from any view only and be used to perform actions for example ID probably in some situations you only need ID for go to detail view or perform a delete action?.

**Comment by zhdanouskikh** [comment]
@diegochavez yes, good idea. In my case it's an additional menu and I don't want it to be shown in columns filter.

**Comment by gregnb** [comment]
this is now available in the latest release as a column option named `viewColumns` take a look at the README

**Comment by william-chu** [comment]
@gregnb Hi Greg, I just used the viewColumns Column option, but didn't see it listed in the Column Options table of the README file. I am happy to make the change and submit a PR, but wasn't sure if it would be easier for you to quickly add it whenever you make your next changes. 

Thanks again!
