### ISSUE TITLE
Set columns width

### ISSUE THREAD

**Issue by jungrafael** [gregnb/mui-datatables#3]
## Issue
Would it be possible to have per column the option to set its width?
That could be an option passed together with the columns array.

## Your Environment

| Tech         | Version |
|--------------|---------|
| mui-datatables  | 1.0.7 |
| node        | 8.7.0 |
| OS      | Ubuntu 17.10 |

**Comment by gregnb** [comment]
Changing the columns data to be an array of objects is something I've been thinking about.  I started this project to make it as easy as possible to get going.  One idea I have is this package could accept two forms of columns.

#1
```
const columns = ["Name", "Company", "City", "State"];
```

#2 (if you need more flexibility)
```
const columns = [
  { 
     name: "name", 
     options: { whateverOptions }  
  }
  ...
];
```

**Comment by gregnb** [comment]
Hey @jungrafael so I've refactored this package to correctly use mui themes and no longer take in options with my own styling system. That was done so it could align properly with material-ui and not having me roll my own solutions. Because of that, I'm not going to provide per component basis styling.  You'll only be able to provide a theme which will affect all or none
