### ISSUE TITLE
Question: Can align text of specific column?

### ISSUE THREAD

**Issue by giovannirosa** [gregnb/mui-datatables#400]
## Body Cell Alignment

I would like to align **specific columns** to the center. Today I can only align all columns or specific header.

I was able to select specific header, but can't do the same for the body cells.

![image](https://user-images.githubusercontent.com/24814967/52140322-a1241a80-2639-11e9-9844-093a0e662fec.png)

Code used:
```
MUIDataTableHeadCell: {
  root: {
    border: 'solid 1px #00FF',
    '&:nth-child(5)': {
       backgroundColor: 'red',
     }
  }
}
```

What I tried and how I would like to do that:
```
MUIDataTableBodyCell: {
  root: {
    border: 'solid 1px #000',
    '&:nth-child(5)': {
       backgroundColor: 'red',
       textAlign: 'center'
    }
  }
}
```

Please advise if there's a way to do that today. Also advise if I can help somehow.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |3.5.1|
| MUI-datatables  |   2.0.0-beta-52   |
| React        |   16.5.2      |
| browser      |   chrome 71.0.3578.98      |
| etc          |         |

**Comment by temporaryGit2018** [comment]
I am also looking for a solution to this!

**Comment by gabrielliwerant** [comment]
`customBodyRender` lets you use any code you want to display the cells of a given column. You can add any styling you want that way.

**Comment by mikroware** [comment]
I am using `setCellProps` on the column options for this as Material-UI `TableCell` already provides a prop `align="right"`. However this does not set any cell props for the header.

I would like to align the header cell also on the right without customizing its content. Because Material-UI already provides the align option, it seems weird to have to implement it myself.

Maybe it is a good idea to add a new option to the column definitions which is forwarded to the `TableCell` align props?

**Comment by gabrielliwerant** [comment]
@mikroware `setCellProps` works, the problem is that you are looking at a version of material-ui that is higher than is used by the project, and the API is different. You need the old `numeric: true | false` option.

**Comment by mikroware** [comment]
Hmm maybe I was not clear. `setCellProps` actually works, but there is no way to do the same for the header cell of that column.

**Comment by gabrielliwerant** [comment]
Have you tried `customHeadRender` in the column options?

**Comment by mikroware** [comment]
Using `customHeadRender` seems to mean I have to re-do the whole cell component myself in order to keep the layout the same as the rest. This looks like a lot of unneeded work when I only want to add one prop to the underlying Material-UI `TableCell` just as with regular columns (`cetCellProps`).

**Comment by gabrielliwerant** [comment]
@mikroware That's correct, it's more effort, but at least for the time being there is a way for you to proceed. It sounds like you have a request for something like `setCellHeaderProps`, which I think is reasonable. If you would like, you can open up a new issue as a feature request so we can discuss and track it.

**Comment by jasraj96** [comment]
In the column options, even though setCellHeaderProps has been added, `setCellHeaderProps: () => ({ align: 'center' })` doesn't seem to have any effect when `sort: true`. 

It seems to be working well when `sort: false`

**Comment by gabrielliwerant** [comment]
`align` on the th won't help you because the column name is wrapped in `flex` display mode when there is a sort button. Also, `align` has been deprecated in HTML, so you actually would need to use `text-align` CSS property instead. But because of `flex` you'll actually need to set `justify-content` and override these styles: `MUIDataTableHeadCell sortAction`.

**Comment by chrishawn** [comment]
this works:
`setCellHeaderProps: () => ({ style: {display: 'flex', justifyContent: 'right', flexDirection: 'row-reverse', borderBottom: 'none'}})`

**Comment by mdrafee03** [comment]
I only added the following code to my jss to make the header center:
```
    MUIDataTableHeadCell: {
      toolButton: {
        justifyContent: 'center !important'
      },
    },
```

**Comment by DangerousDetlef** [comment]
Wow, okay, so this was a long journey just to get a specific column's header centered.

Now first, there are two solutions here that won't work quite well.
@chrishawn proposed this:
`setCellHeaderProps: () => ({ style: {display: 'flex', justifyContent: 'right', flexDirection: 'row-reverse', borderBottom: 'none'}})`

This works, but only to a degree. Tried changing resolution so you need to scroll? The headers that have this (as he admitted) dirty hack don't stick because they need `display: table-cell`, which is overwritten by the `display: flex`. But without this, it won't center. So no solution here.

@mdrafee03 proposed this:
```
  MUIDataTableHeadCell: {
      toolButton: {
        justifyContent: 'center'
      },
    }
```

This also works, but only for **all** cell headers. Mostly, of course, you want to change the alignment of a specific cell header. The first solution does this, but imperfectly. This one doesn't. But we can combine both solutions and get where we want.

`MUIDataTableHeadCell.toolButton` is the `span` that is a child of the `th` which is modified in `setCellHeaderProps`. So we need to somehow get to this child `span` from `setCellHeaderProps`.

The solution:
First, we add a new JSS class for the cell header we want to have centered (or aligned in any other way than left). In this JSS class, we will implement a child selector that targets the `span` element.

```
 centeredTableHead: {
    '& > span': {
      justifyContent: 'center',
    }
  }
```

We will then pass the this class into our MUIDatatable for creating the columns. However you do this, is up to you. you can do this via props like in the Example from [here](https://github.com/gregnb/mui-datatables/blob/master/examples/customize-styling/index.js) or if you use mainly functional components (like me) you can use the Material UI way of `const classes = useStyles()` and pass those in a function that creates the column. 

Now we just need to add this class to the specific cell header using `setCellHeaderProps`. To do so, we can simply use clsx which already ships with MaterialUI. This can look something like this (short version):

```
function CreateColumns(classes) {
  const columns = 
  [
    {
      name: 'Test',
      label: 'Test',
      options: {
        setCellHeaderProps: () => {
          return {
            className: clsx({
              [classes.centeredTableHead]: true,
            })
          }
        }
      }
    }
  ]

  return columns;
} 

...

const classes = useStyles();
const columns = CreateColumns(classes);

<MUIDataTable 
    title="Test"
    className={classes.paper}
    options={options}
    columns={columns}
    data={data}
/>
```
And that's it. Simply add the class via cslx in the `setCellHeaderProps` for every table header that should be centered and it works.

However, I think it's far to complicated for such a simple task. There should be a simple option to this somewhere else. Would you be open to an issue request adding such an option, @patorjk ?

**Comment by patorjk** [comment]
Looks like you came to the same solution I did (https://github.com/gregnb/mui-datatables/issues/1258#issuecomment-662522545), I'm not aware of a better way. It doesn't seem too complex, especially with hooks. However, I'd be open to a PR to make it simpler.

**Comment by danielh186** [comment]
@patorjk 
So the sorting arrows in your example seem to be a bit shifted in y-direction. Also with some new version came that the element for changing the  sorting direction is now a <button> and not anymore a <div>. So your styling isn't quite working properly anymore.

Because I had the same problem and just fixed it for me, I thought I might as well post my solution to it (working for mui-datatables v.3.7.7) It is really similar to your approach but just with some different styling (located in styles.css but you could use styled modules as well)

https://codesandbox.io/s/react-muidatatable-centered-header-qtkiw?file=/src/App.js

A little bit offtopic question:
In my codesandbox I tried to get borders around every table cell. But somehow the tableHeader cells just won't take a borderRight. I want it to look just like in the picture @giovannirosa posted at the top of this Issue but the code he posted won't work for my version of mui-datatables (v.3.7.7).
Is there someone that knows how to get the table to have full borders just like a normal html <table> ?

**Comment by zulfiqar313** [comment]
cost columns = [ {
    field: 'checkNo',
    headerName: 'Payment Check#',
    width: 150,
    align: 'center',
  }]
  provide align center if you want to center align the content of a specific column.

**Comment by kitaroar** [comment]
I changed the align of cells with this code in column options

setCellHeaderProps: () => { return { align:"center"} },
setCellProps: () => { return { align:"center"} },

My problem is when the table is displayed on small screens and the responsive option is set to 'vertical' or  'simple', these columns keeps the alignment to center and the rest of cells is aligned to left.

Can I use some code to align those cells in responsive mode to default align?

![Screenshot_2](https://user-images.githubusercontent.com/31425662/160832839-2e3aa0a9-1ce5-44b8-ab8d-4fcbc0312ef3.png)
![Screenshot_3](https://user-images.githubusercontent.com/31425662/160832859-a9efbd2e-d4e1-4572-b041-8ac4bd4080c5.png)

**Comment by MickaelAustoni** [comment]
You can use `@mui/x-data-grid` with `headerAlign` &  `align` attribue.

``` typescript tsx
import { DataGrid, GridColDef } from "@mui/x-data-grid";

const columns: GridColDef[] = [
  { field: "firstName", headerName: "First name", width: 130 },
  { field: "lastName", headerName: "Last name", width: 130 },
  {
    align: "center",
    field: "age",
    headerAlign: "center",
    headerName: "Age",
    type: "number",
    width: 90,
  },
];

const rows = [
  { age: 35, firstName: "Jon", id: 1, lastName: "Snow" },
  { age: 42, firstName: "Cersei", id: 2, lastName: "Lannister" },
];

<DataGrid rows={rows} columns={columns} />
```
