### ISSUE TITLE
V2.0.0-beta-59 Can't resolve '@material-ui/icons/FileDownload' 

### ISSUE THREAD

**Issue by jkeruzec** [gregnb/mui-datatables#539]
I've the impression to run on this to time to time very strange.
I've just upgraded from 2.0.0-beta-54 to 2.0.0-beta-59.

Can you check ?
Thanks,

**Comment by jkeruzec** [comment]
trying the #515

**Comment by Legogris** [comment]
This issue seems to come from that the versioning scheme has silently changed since beta 55 - latest version is `2.0.0-beta.59` as opposed to `2.0.0-beta-59` (previous scheme). Referencing `^2.0.0-beta-59` had me end up on `2.0.0-beta-9`.

https://www.npmjs.com/package/mui-datatables?activeTab=versions

**Comment by jkeruzec** [comment]
That's weird to change convention naming during the project... 
Because when you are changing from this to that :
![image](https://user-images.githubusercontent.com/3499632/55938465-bd48c700-5c3b-11e9-8af0-ce8cd1d58e81.png)

That's is my case, you cannot gest that you have to put a . instead of - like this ... Especially using some automatic dependency finder like npm-upgrade ..

**Comment by gregnb** [comment]
Yes, this is something I had screwed up initially by not using dots. That's why I made the change.
