### ISSUE TITLE
implementation of new feature... question

### ISSUE THREAD

**Issue by matteo1976** [gregnb/mui-datatables#621]
I'm new and it's my first time working on a project at GitHub.
I'm working on a feature, to add a row to the table by entering data through a modal form.
when it's over, will it be possible to make a pull-request in a branch so that other people can also work and/or correct this feature? #

**Comment by gabrielliwerant** [comment]
Do you mean a personal project of yours? If so, that will be up to you, and you could make it public and see if people would benefit and help you out.

If instead you mean adding a modal form feature to the `mui-datatables` project, I think that would be out of scope for this library at the moment. I would prefer to leave those kinds of use cases to individual users to create so that the library here doesn't become too bloated, which is the tendency of all libraries over time. Maybe such a thing could be revisited in the future, but it would be unlikely to be soon.

**Comment by matteo1976** [comment]
ok thanks!

**Comment by matteo1976** [comment]
Sorry I'm new in the use of Github as collaborator... I have just see now ...there is a CustomToolbar and CustomToolbarSelect.... that is what i want... Now I understand...
