### ISSUE TITLE
customRender - index variable the row number? Can I get the column?

### ISSUE THREAD

**Issue by teadams** [gregnb/mui-datatables#63]
I tested out custom Render and I believe the index passed to my function is the index of the row.  Is there a way to get access to the column?

I'm trying to build a way to "in line edit" a cell.   Use case
a) user clicks on cell
b) cell changes to input box
c) when user leaves cell, update function is called

**Comment by gregnb** [comment]
I'll look into this might not be a bad idea to include the cell location

**Comment by teadams** [comment]
Please :)  Right now I have a nasty hack where I sneak the column through the data.  But other that that, it works awesome.

**Comment by teadams** [comment]
Thanks...  I was able to get the row information because my handleCustomRender has access to the data array.  However, it would be far easier to directly have access to it in custom render. 

This is the code 
```js
handleCustomRender(index, value, updateValue) {
    // index of column that contains the database key data
    const id_column_index = 0;

    /// THIS IS MY HACK TO WORK AROUND NOT KNOWING THE INDEX
    /// I pass the column in the fields of the data array
    var cell_data = value.split('//**//');
    var column = cell_data[0];  /// index of the column
    var value = cell_data[1];   /// original value before hack
    
    // in one case of using custom Render, it was using an index that was larger 
    // than size of the data.  This next line was to protect from that.
    if (this.state.data[index]) {
      // Get the data from the row that contains the ID
      id_column_value = this.state.data[index][id_column_index].split('//**//')[1];
    }

    return <Cell value={value}  column={column} id_column_value={id_column_value}  onUpdate={this.handleInlineUpdate}  />
}
```

**Comment by gregnb** [comment]
@teadams @jkantr I'm open to feedback on how either of you envision some changes toe customRender() in terms of structure. Let's see some quick mockups. How would we structure the additional params? 

The current version is in beta so I am fine with making the right breaking change to give everyone lots of flexibility going forward.

Current:
```
handleCustomRender(index, value, updateValue) {
```

Becomes this:
```
handleCustomRender(updateValueFn, data) {
```
and data is an object where we could list as mentioned above a structure like the following:

```
data = {
  cellData,
  rowData,
  rowIndex,
  columnIndex,
}
```

I'm not crazy for naming the parameter `data` could use some help there. Thoughts? @jkantr I saw you had 'type' listed but what would that mean?

**Comment by teadams** [comment]
Maybe the  Column Options for that column?

1. This would support the existing options that you have defined, plus any extra options the developer added.
2. This will serve as a way to pass any column specific options to the customRender function.  (parallels column options for the full row)

**Comment by teadams** [comment]
I think data might be confused with the overall table data.

Some other ideas
cell_vars
cell_params
cell_vals
cell_attributes
cell_props
cell_state
vars
params
vals
attributes

**Comment by jkantr** [comment]
I guess this isn't a simple interface to design because the idea of a "custom" render is very general, but not very generalizable. Many cases it's just styling the data differently or only truncating it or wrapping it in some other tags or another component etc. But sometimes you're rending a custom column to have icons in it and no data, or an expandable button or something. Sometimes you want to have some sort of calculated data that's just a combination of data available elsewhere.

In *theory* all of this could be done when the data is being prepared to give to the component.. but there are advantages i think to having this behavior defined in the table (or column, in this case) as opposed to in the data transport interface. Especially in terms of rendering optimization.

One important thing to me is that the `customRender` function should be able to do its job *without lexical/external access to the table data*. I think the only way to keep the API clean is to make sure the fn is encapsulated with all the data it needs (as is, at the time it's called).

So option 1 is we put the most common use cases first, which is `cellData` (or `cellValue`?) and then we combine the rest of the data by its relation to the cell, so `context` (or `related`?) which would be things like the `rowData`, `rowIndex` and `columnIndex`... and then the `meta` which are things like the settings/state for the column `filter`, `sort`, `sortDirection`, `display` (or visibility?) and `name`. I believe this would cover most usecases I could think of... and at least by dividing them categorically we could expose something else later on without a breaking change.

I still have 1 other similar issue with accessing certain data from certain fields but I'll probably start another thread about it as i don't think it has anything to do directly with this fn's arguments.

**Comment by gregnb** [comment]
@jkantr Can you put together in one mock up function what you see for parameters and contents of any data objects

**Comment by samsch** [comment]
I'm doing some work with this library, and I need the row data available to my custom render. Specifically, my custom render uses an onEdit for a button which needs to be called with the row ID.

I think this would be a good shape: `customRender(value, updateValueFn, meta)`, where meta is
```js
{
  rowData,
  tableData,
  rowIndex,
  columnIndex,
  columnName,
  tableState: { /* filter, sort, selected, state etc. */ }
}
```
The tableState stuff isn't particularly important to what I'm doing personally, I added that in based on @jkantr last post.

**Comment by jkantr** [comment]
Having it all together in one value doesn't feel great... but it's almost arbitrary to try to split it up. I would probably opt for `customRender(value, data = { rowData, tableData }, meta = { rowIndex, columnIndex, columnName, tableState, updateValueFn` - probably only because having the 'callback' (or event trigger? w/e) function last seems more 'normal' to me.

But realistically I don't think any of this matters much. As long as the stuff is available and it's documented it's probably fine.

**Comment by gregnb** [comment]
I think I'm going to go with the following (and may actually start work on it today)

```
handleCustomRender(index, value, updateValue) 
```
	to
```
handleCustomRender(value, tableMeta, updateValue)
```

```
tableMeta {
 rowIndex,
 columnIndex,
 columnName,
 rowData,
 tableData,
 tableState: { /* filter, sort, selected, state etc */ }
}
```

**Comment by jkeruzec** [comment]
it seems that nothing is rendered with the change.. 
I return either a String or a component but column is empty/not displayed at all.

![image](https://user-images.githubusercontent.com/3499632/41921902-370d6408-7964-11e8-9281-cd27dc266a5f.png)

With : 

```js
{
                name: "Edit",
                options: {
                    filter: false,
                    customRender: (value, tableMetadata, updateValueFn) => {
                        return <IconButton><EditIcon /></IconButton>;
                        }
                }
            }
```

**Comment by gregnb** [comment]
@jkeruzec Yeah, it's weird when running locally as dev it works fine but I see some issues on prod bundles. let me look into this

**Comment by gregnb** [comment]
@jkeruzec Which version are you running? Make sure it's the latest beta. 

Take a look at this codesandbox I put up with the same example that is in examples/ looks good here

https://codesandbox.io/s/w7zm4zm0r5

**Comment by jkeruzec** [comment]
Ok my bad, I was providing an array with on data less than the number of column... !

Thanks anyway !

**Comment by ivaqmo123** [comment]
Hi Greg, 
When TableMeta.rowData is supposed to retrieve the full row data as an array. But as you can see in image below, rowData is only showing the value of the raw associated to the column (not the entire row as array). Could you please advise?

![image](https://user-images.githubusercontent.com/30051512/49700313-0106c380-fbab-11e8-8296-0b24d7cf6e78.png)

**Comment by vishalc10** [comment]
@ivaqmo123 Having same issue, lemme know if you find a solution to it. Thanks

**Comment by jlucier** [comment]
I'm also seeing that `tableMeta.tableData` is an empty list.

**Comment by gabrielliwerant** [comment]
Opened a new issue to address some of the issues with `tableMeta` https://github.com/gregnb/mui-datatables/issues/901.
