### ISSUE TITLE
Filter treats all items in a cell as one

### ISSUE THREAD

**Issue by seta-hungDang** [gregnb/mui-datatables#633]
Hi everyone! I  ran into a problem when I have a bunch of tags for a table and the tags need to be filtered from time to time. But if one item have more than two tags then the filter will just consider them as one.

## Expected Behavior
 - A group of tags will appear separately in the filter options

## Current Behavior
 - All items of one table cell is considered as one

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |v1.0.0       |
| MUI-datatables  |   2.0.0-beta      |
| React        |    16.3.2     |
| browser      |    Chrome v74     |
| etc          |         |

**Comment by gabrielliwerant** [comment]
Hello! I'm having some difficulty understanding precisely what the problem is. Some things you can do to help clarify this are as follows:

- Add screenshots or screen captures with annotations
- Add a codesandbox example illustrating the problem
- Provide steps to reproduce

Also, try to be mindful of your terminology. When you say "tags," I think you mean applied filters, but I'm not 100% sure.

**Comment by seta-hungDang** [comment]
@gabrielliwerant Sorry for the confusion. After reading more issues, I found this #403 that is similar to what I need. I'm going to close this issue and watch that one. Thank you for your swift reply!

**Comment by gabrielliwerant** [comment]
@seta-hungDang No worries, will follow up in the older issue.
