### ISSUE TITLE
MUIDataTable cannot customize  count

### ISSUE THREAD

**Issue by rst66** [gregnb/mui-datatables#75]
There are no prop or option to customize the total number of rows, which is  the ``count`` prop
of ``TablePagination`` . 

This attribute is the ``length`` of the data, but in my case, only one page of data is pulled from backend service, with  the ``total`` attribute. I think this is the common case, so it will be very necessary to be able to customize the ``count``.

## Expected Behavior
add ``count`` in ``options`` prop of MUIDataTable

## Current Behavior
no such option

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    1.0.0-beta.41     |
| MUI-datatables  |  1.1.4       |
| React        |  16.3.1       |
| browser      |     chrome    |

**Comment by adetwiler** [comment]
I am having the same issue, I think the real enhancement here would be to support remote datasources in general. Such as sorting, filtering, searching, pagination, etc.

Currently this only seems to support an entire datasource rather than a paginated datasource either from a remote or local source. It would be nice to get further support on that rather than it just being limited to needing the entire dataset.

**Comment by jstgermain** [comment]
Having the same exact issue, and I have come to the same conclusion as @adetwiler. This has halted development and forced me to download the git repo instead of the NPM module. It seems like I have it really close to working with remote data, but issues in filters, searching, and pagination. This module is amazing, but it seems odd that it wasn't built to handle remote data with an offset and limit instead of a full data set. I look forward to seeing further releases and hope to not have to fork my own version. This has really spread up development till the remote data issue came into play.

**Comment by gregnb** [comment]
I will add count property to the options prop. Hope this will address all your issues

**Comment by floscom** [comment]
yeah would be great!
