### ISSUE TITLE
Update columns without refreshing data?

### ISSUE THREAD

**Issue by anthomaxcool** [gregnb/mui-datatables#784]
I'm using the datatable in a translatable page (using react-i18next - not needed to reproduce) and I want the columns to be translated as well so I'm setting the column's label like this : `label: t('path.to.text');`. It works well, however, the columns won't re-render unless the data is empty.

I get around the problem by doing the following, but it's ugly (won't work without setTimeout) :

```
let tempData = this.state.data;
this.setState({data: []});
...
setTimeout(function() {
    this.setState({data: tempData});
}, 0);
```

## Expected Behavior

I think the datatable should be able to modify the columns with data in it.
## Current Behavior

Columns won't change unless the datatable is empty.
## Steps to Reproduce (for bugs)

1. Create a table
2. Add a button that will change the column label
3. Click on it

https://codesandbox.io/embed/young-smoke-1z2f6

Make sure you view the datatable "full width" in order to see the changed label or else the columns are displayed on the left and will be hidden if there's no data.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |  4.2.1  |
| MUI-datatables  |  2.6.4  |
| React        |  16.8.6  |
| browser      |  Chrome 75.0.3770.100 64 bits   |

**Comment by gabrielliwerant** [comment]
The issue comes from maintaining all the column data/options in state. The way the table works at the moment, changes in the columns object causes a refresh of the table state, which can erase the state you're interested in preserving.

The fix is to take columns out of state and maintain only the values you wish to change in state. I've created a working example based on the example you created here: https://codesandbox.io/s/agitated-silence-k51px?fontsize=14.

**Comment by anthomaxcool** [comment]
Thank you this is exactly what I was look for!
