### ISSUE TITLE
How to detect focused row when changed with the keyboard

### ISSUE THREAD

**Issue by scresawn** [gregnb/mui-datatables#810]
When a row is clicked using a mouse/trackpad, this can be detected using the onRowClick event. However, I don't see a similar event to detect when a user changes the focused row by using the up or down arrow keys, even though the highlighted row in the table does change. Is there a way to do this?

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |   4.2.1      |
| MUI-datatables  |     2.6.3    |
| React        |     16.8.6    |

**Comment by gabrielliwerant** [comment]
I don't think rows can be focused at all using up or down keys right now, so firstly, I'm not sure how you've achieved that behavior! :) But secondly, the answer right now is certainly no, since it's even possible to focus at all, as far as I can tell (except for the checkboxes under default settings).

There may be a good case for a new feature here to add such a thing, but first I'd to be sure about what you're trying to do and how it works for you at the moment.

**Comment by gabrielliwerant** [comment]
Also, make sure you're on the latest release, as there were issues with row selection which were patched, so what you're describing as existing now might have actually been unintended behavior as the result of a bug.

**Comment by scresawn** [comment]
That's interesting. And for what it's worth, I can't reproduce the behavior myself. I'll go ahead and close this now.
