### ISSUE TITLE
Link not working in customRowRender

### ISSUE THREAD

**Issue by buddies2705** [gregnb/mui-datatables#823]
Problem - Link is not clickable (See CoinRow component)

<Removed unnecessary code>

**Comment by gabrielliwerant** [comment]
There is a lot going on here, can you strip this down to a minimal example that demonstrates something incorrect with that table, and then post it to codesandbox so that we're on the same page with dependencies and everything else?

If I take an existing example from the examples section of the codebase, say `customize-filter`, and I add `customBodyRender: value => <td><a href="http://google.com">{value}</a></td>` to one of the columns, I don't have any trouble clicking it. It would be helpful if you could take something simple and build up until the very moment it breaks. Since I am able to get this to work in a simple example, it's likely the issue results from some complication outside of the table itself.

**Comment by buddies2705** [comment]
Hey @gabrielliwerant sorry for being inconsiderate.

I stipped everything but seems customRowRender not working.

https://codesandbox.io/embed/muidatatables-custom-toolbar-zfbsi

**Comment by gabrielliwerant** [comment]
Thank you for posting the example. In your example, your version of mui-datatables is too low. `customRowRender` was not available as a feature until `3.2.0`.

**Comment by buddies2705** [comment]
I am using 2.8.0 (This is the latest version correct?).. I think I narrow down the problem, Somehow <Link> is not working but <a> is working. 

https://codesandbox.io/s/muidatatables-custom-toolbar-lh444

**Comment by gabrielliwerant** [comment]
Oops, I should have said `2.2.0` above. Yes, now you have the correct version of mui-datatables, but your version of material-ui is too low. You need a version of material-ui that supports the `Link` component. You can either upgrade material-ui until it works, or you can use anchor tags instead and it will work on a lower version.

**Comment by gabrielliwerant** [comment]
Considering this resolved and closing. If there's a demonstrable bug here, we can re-open,
