### ISSUE TITLE
doesn't delete row onRowDelete cb function

### ISSUE THREAD

**Issue by laurexas** [gregnb/mui-datatables#830]
## Expected Behavior

when calling onRowDelete selected row should be deleted in UI.

## Current Behavior

Hello, didn't see anyone else had the same problem besides me so i noticed a problem when calling onRowDelete callaback function..When row is selected and deleted call back function onRowDelete is called which calls redux action in store/actions folder in my code to delete specific index from server, but for some reason selected row in UI datatable is not deleted, but if i use simple api delete method in callback function  without calling redux action it works perfectly fine, any ideas why this may be happening?
## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  | 3.9.2        |
| MUI-datatables  |    ^2.6.4     |
| React        |     16.8.2    |
| browser      |     chrome    |
| etc          |         |

**Comment by gabrielliwerant** [comment]
If the problem doesn't exist prior to adding redux, then it's likely that the issue lies in the redux implementation somewhere. In testing this locally, I can't find an issue function itself (though that doesn't mean it isn't there).

What I would do is create the simplest table example that works and then slowly add code until it breaks. At that point, if you post it to a codesandbox, I can take a closer look.

**Comment by laurexas** [comment]
got it, ill try to reproduce my code  example in sandbox and will look for errors.

**Comment by laurexas** [comment]
coudn't find the error in my redux code, so i used  a workaround after delete request i updated my data props and that initialized table to rerender.

**Comment by gabrielliwerant** [comment]
Were you able to find a breaking example without redux?
