### ISSUE TITLE
CustomRowPopover option

### ISSUE THREAD

**Issue by rhaicode** [gregnb/mui-datatables#914]
For larger data that have more than 10 columns, the current datatable offers horizontal scrolling to view the other columns of data. That is intuitive. 

However, if the user wants to review data that are located somewhere on the first columns, the user needs to horizontally scroll the table again - affecting user experience.

I would like to suggest a new option, CustomRowPopover, that would be receiving rowData and rowMeta, which returns a component (just like CustomFooter or CustomColumn). 

In that way, if the user wants to review the summary of the whole data of a row, he just have to hover over a row and expect a popover.

**Comment by gabrielliwerant** [comment]
This is functionality you can provide for yourself now, by using `customRowRender` to provide your own row component with tooltip, or whatever hover effects you'd like.

Although I appreciate the suggestion, this library is better off not offering specific solutions to complex problems because it opens endless branches for variations not considered as well as potential maintenance overhead and general code bloat. I don't really want to offer a default answer to the enormous-table-problem because there are too many UX considerations to take into account.

If you'd like to work on an example using `customRowRender` with tooltips or something, I'd gladly consider adding that to the examples section in this repo, so that like-minded devs can benefit.

**Comment by rhaicode** [comment]
Sure thing. I will try to work on it and submit a PR in the future. The example would be called as custom-row-popover that uses customRowRender.
