### ISSUE TITLE
Filter Chips are getting concatenated in filterType 'custom' mode, incompatible with multi-select.

### ISSUE THREAD

**Issue by buwanekab** [gregnb/mui-datatables#937]
When column with filterType `custom` mode and with multi-select options. filter chips are getting concatenated in the same chip, when select on multiple options.

## Expected Behavior
filterType `custom` with multi-select options should support for multiple chips to be displayed in the chips list. Like in the current filterType `multiselect` mode.

### FilterType with `custom`
**Filter Options :**
Multiple options are selected.
![image](https://user-images.githubusercontent.com/53601805/65218490-36debe00-dad4-11e9-9060-8d2aa5c0ebe9.png)

**Chip :**
All selected options are concatenated into single chip.
![image](https://user-images.githubusercontent.com/53601805/65218395-01d26b80-dad4-11e9-8f5a-577bc67f6657.png)

### FilterType with `multiselect`
**Chip :**
All selected options are displayed as separate chips.
![image](https://user-images.githubusercontent.com/53601805/65218804-e3b93b00-dad4-11e9-8b6e-173ae24edd8b.png)

## Analysis
I have investigated mui-datatable `TableFilterList.js` component, and i found that, the filterType `custom` doesn't handle multi-values in the `filterList[index]`
https://github.com/gregnb/mui-datatables/blob/f0ea9e58d82839c57a4dfd4a342b6649932660a7/src/components/TableFilterList.js#L44

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |   4.3.3   |
| MUI-datatables  |   2.11.1   |
| React        |   16.9.0   |
| browser      |   any   |

**Comment by gabrielliwerant** [comment]
Hello @buwanekab. So, if you are using `filterType: "custom"`, then you are required to supply your own filter component and logic, and so on. That means that you have to make your own multiselect component. Given that, I'm not sure that `custom` is really what you're looking for. Why doesn't simply using `multiselect` work for you?

**Comment by gabrielliwerant** [comment]
I think I'll need to see a sample of code that isn't working to be of more help. Can you post something to codesandbox?

**Comment by buwanekab** [comment]
@gabrielliwerant ,
can check on this codesandbox example :
https://codesandbox.io/s/monitoring-dashboard-hhb42?fontsize=14
FYI - 
`custom` filterType in  `Alert Source`
`multiselect` filterType in  `Alert Severity`

**Comment by promerorgz** [comment]
Not sure if youve solved this yet but I came across this same issue.

The issue is in the `customFilterListRender` fn and it depends how many options youve selected.  If you select one option then it looks like the value is a string and it renders in the chip. When you select multiple, it renders the contents of the array in the same chip.

What I did (and there's probably a better way to do this) was to check if `value` is an Array. If it is, then I iterate through the array and return each value separately. If its not an array then I just return the value. 

Here's an example; I use ramda for the helper functions. 

```js
customFilterListRender: value => {
            if (!R.isEmpty(value)) { 
                return R.is(Array, value) 
                         ? value.forEach(item => item || '(blank)') 
                          : item || '(blank)'
            }
            return false
        }, ```

**Comment by buwanekab** [comment]
@promerorgz ,
Thanks for your suggestion.
I have a question, In your solution, you have used ternary operation to return values, based on the input value from `customFilterListRender`. So, in there my doubt is that you are returning undefined value if it is an array. `value.forEach(item => item || '(blank)')`, since `forEach` return type is undefined,

But anyway, i tried with my sandbox. still the same. now its giving different error due to undefined return.

**Comment by gabrielliwerant** [comment]
I've looked into this more deeply, and this isn't actually a bug, it's a non-existent feature. The way custom filter list renderers work now, they only support single values, not arrays of values. Quite a few things need to change about filters in order to accommodate this, including a necessary additional option to supply your on delete function for custom filter list renders, since otherwise the code won't know how it's supposed to modify the filterList array in situations where you have multiple items. It's not the same as multiselect, because multiselect makes decisions about how to remove elements from the filterList array that can't be guaranteed if you're using custom logic (in particular, the custom filter example will break if using multiselect logic).

I'm working on something now, but I'm not guaranteeing anything as there's a lot of work and many opportunities for regressions that I have to be careful about.
